namespace :load_subcategories do
	desc "Seeds database with careerone subcategories"
	task :career_one => :environment do
		subcategories = [
			{ external_subcategory_id: 15432, category_name: "Accounting", name: "Accounts Clerk & Administration" },
			{ external_subcategory_id: 11711, category_name: "Accounting", name: "Accounts Payable & Accounts Receivable" },
			{ external_subcategory_id: 11712, category_name: "Accounting", name: "Actuarial & Analysis" },
			{ external_subcategory_id: 11803, category_name: "Accounting", name: "Analyst" },
			{ external_subcategory_id: 15433, category_name: "Accounting", name: "Assistant & Part-Qualified Accountants" },
			{ external_subcategory_id: 11724, category_name: "Accounting", name: "Audit" },
			{ external_subcategory_id: 11730, category_name: "Accounting", name: "Bookkeeping" },
			{ external_subcategory_id: 14868, category_name: "Accounting", name: "CFOs & Financial Controllers" },
			{ external_subcategory_id: 11744, category_name: "Accounting", name: "Chartered Accountants & CPAs" },
			{ external_subcategory_id: 11750, category_name: "Accounting", name: "Collections" },
			{ external_subcategory_id: 11766, category_name: "Accounting", name: "Credit" },
			{ external_subcategory_id: 14867, category_name: "Accounting", name: "Financial Accounting & Management Accounting" },
			{ external_subcategory_id: 11804, category_name: "Accounting", name: "Financial Planning & Advising" },
			{ external_subcategory_id: 11817, category_name: "Accounting", name: "Fund Accounting & Management" },
			{ external_subcategory_id: 15434, category_name: "Accounting", name: "Insolvency & Corporate Recovery" },
			{ external_subcategory_id: 11843, category_name: "Accounting", name: "Investment Management" },
			{ external_subcategory_id: 11893, category_name: "Accounting", name: "General/Other - Accounting" },
			{ external_subcategory_id: 11918, category_name: "Accounting", name: "Payroll & Benefits Administration" },
			{ external_subcategory_id: 15435, category_name: "Accounting", name: "Procurement & Inventory" },
			{ external_subcategory_id: 14875, category_name: "Accounting", name: "Real Estate Leasing & Acquisition" },
			{ external_subcategory_id: 11952, category_name: "Accounting", name: "Risk Management & Compliance" },
			{ external_subcategory_id: 11960, category_name: "Accounting", name: "Stockbroking" },
			{ external_subcategory_id: 11981, category_name: "Accounting", name: "Tax Accounting" },
			{ external_subcategory_id: 11982, category_name: "Accounting", name: "Tax Assessment & Collections" },
			{ external_subcategory_id: 11760, category_name: "Accounting", name: "Treasury & Corporate Finance" },
			{ external_subcategory_id: 11927, category_name: "Accounting", name: "Underwriting" },
			{ external_subcategory_id: 11713, category_name: "Administration & Secretarial", name: "Administration" },
			{ external_subcategory_id: 11770, category_name: "Administration & Secretarial", name: "Data Entry" },
			{ external_subcategory_id: 11802, category_name: "Administration & Secretarial", name: "Filing & Records Management" },
			{ external_subcategory_id: 11888, category_name: "Administration & Secretarial", name: "Office Management" },
			{ external_subcategory_id: 11894, category_name: "Administration & Secretarial", name: "General/Other - Administration & Secretarial" },
			{ external_subcategory_id: 11797, category_name: "Administration & Secretarial", name: "Personal & Executive Assistants" },
			{ external_subcategory_id: 14874, category_name: "Administration & Secretarial", name: "Property & Asset Management" },
			{ external_subcategory_id: 11942, category_name: "Administration & Secretarial", name: "Reception" },
			{ external_subcategory_id: 11958, category_name: "Administration & Secretarial", name: "Secretarial" },
			{ external_subcategory_id: 15452, category_name: "Advertising, Media, Arts & Entertainment", name: "Agency & Account Management" },
			{ external_subcategory_id: 11758, category_name: "Advertising, Media, Arts & Entertainment", name: "Copywriter" },
			{ external_subcategory_id: 11765, category_name: "Advertising, Media, Arts & Entertainment", name: "Creative Direction & Creative Lead" },
			{ external_subcategory_id: 11752, category_name: "Advertising, Media, Arts & Entertainment", name: "Digital Media" },
			{ external_subcategory_id: 11800, category_name: "Advertising, Media, Arts & Entertainment", name: "Fashion & Accessories" },
			{ external_subcategory_id: 11821, category_name: "Advertising, Media, Arts & Entertainment", name: "Graphic Design" },
			{ external_subcategory_id: 11837, category_name: "Advertising, Media, Arts & Entertainment", name: "Industrial Design" },
			{ external_subcategory_id: 11719, category_name: "Advertising, Media, Arts & Entertainment", name: "Interior Design" },
			{ external_subcategory_id: 11850, category_name: "Advertising, Media, Arts & Entertainment", name: "Journalist" },
			{ external_subcategory_id: 11868, category_name: "Advertising, Media, Arts & Entertainment", name: "Media & Advertising Sales" },
			{ external_subcategory_id: 11869, category_name: "Advertising, Media, Arts & Entertainment", name: "Media Planning & Buying" },
			{ external_subcategory_id: 15454, category_name: "Advertising, Media, Arts & Entertainment", name: "Museum & Arts" },
			{ external_subcategory_id: 11897, category_name: "Advertising, Media, Arts & Entertainment", name: "General/Other - dvertising, Media, Arts & Entertainment" },
			{ external_subcategory_id: 11919, category_name: "Advertising, Media, Arts & Entertainment", name: "Performers, Entertainers & Models" },
			{ external_subcategory_id: 11923, category_name: "Advertising, Media, Arts & Entertainment", name: "Photography" },
			{ external_subcategory_id: 11864, category_name: "Advertising, Media, Arts & Entertainment", name: "Production & Traffic" },
			{ external_subcategory_id: 15455, category_name: "Advertising, Media, Arts & Entertainment", name: "Publishing" },
			{ external_subcategory_id: 11795, category_name: "Advertising, Media, Arts & Entertainment", name: "Sponsorship, Promotions & Event Management" },
			{ external_subcategory_id: 15456, category_name: "Advertising, Media, Arts & Entertainment", name: "Strategic Planning" },
			{ external_subcategory_id: 11723, category_name: "Advertising, Media, Arts & Entertainment", name: "TV, Film & Radio" },
			{ external_subcategory_id: 12005, category_name: "Advertising, Media, Arts & Entertainment", name: "User Interface (UI), User Experience (UX) & Web Design" },
			{ external_subcategory_id: 11716, category_name: "Agriculture, Nature & Animal", name: "Agriculture, Harvesting & Horticulture" },
			{ external_subcategory_id: 15436, category_name: "Agriculture, Nature & Animal", name: "Animal Husbandry & Livestock" },
			{ external_subcategory_id: 15437, category_name: "Agriculture, Nature & Animal", name: "Conservation & Natural Resources" },
			{ external_subcategory_id: 15438, category_name: "Agriculture, Nature & Animal", name: "Equine Industry" },
			{ external_subcategory_id: 11806, category_name: "Agriculture, Nature & Animal", name: "Fishing, Marine & Aquaculture" },
			{ external_subcategory_id: 15439, category_name: "Agriculture, Nature & Animal", name: "Forestry" },
			{ external_subcategory_id: 15440, category_name: "Agriculture, Nature & Animal", name: "Services & Consultancy" },
			{ external_subcategory_id: 12001, category_name: "Agriculture, Nature & Animal", name: "Veterinary & Zoology" },
			{ external_subcategory_id: 15441, category_name: "Agriculture, Nature & Animal", name: "Wine & Viticulture" },
			{ external_subcategory_id: 11803, category_name: "Banking & Finance", name: "Analyst" },
			{ external_subcategory_id: 15442, category_name: "Banking & Finance", name: "Banking Operations" },
			{ external_subcategory_id: 11726, category_name: "Banking & Finance", name: "Branch Staff" },
			{ external_subcategory_id: 15226, category_name: "Banking & Finance", name: "Business Banking & Credit" },
			{ external_subcategory_id: 15443, category_name: "Banking & Finance", name: "Business & Corporate Banking" },
			{ external_subcategory_id: 11750, category_name: "Banking & Finance", name: "Collections" },
			{ external_subcategory_id: 11804, category_name: "Banking & Finance", name: "Financial Planning & Advising" },
			{ external_subcategory_id: 11817, category_name: "Banking & Finance", name: "Fund Accounting & Management" },
			{ external_subcategory_id: 11843, category_name: "Banking & Finance", name: "Investment Management" },
			{ external_subcategory_id: 15229, category_name: "Banking & Finance", name: "Mortgage, Financing & Lending" },
			{ external_subcategory_id: 15444, category_name: "Banking & Finance", name: "General/Other - anking & Finance" },
			{ external_subcategory_id: 15445, category_name: "Banking & Finance", name: "Retail Banking" },
			{ external_subcategory_id: 11952, category_name: "Banking & Finance", name: "Risk Management & Compliance" },
			{ external_subcategory_id: 11960, category_name: "Banking & Finance", name: "Stockbroking" },
			{ external_subcategory_id: 11760, category_name: "Banking & Finance", name: "Treasury & Corporate Finance" },
			{ external_subcategory_id: 11729, category_name: "Biotech, R&D, Science", name: "Biological & Chemical Research" },
			{ external_subcategory_id: 11749, category_name: "Biotech, R&D, Science", name: "Clinical Research" },
			{ external_subcategory_id: 11790, category_name: "Biotech, R&D, Science", name: "Environmental/Geological Testing & Analysis" },
			{ external_subcategory_id: 15446, category_name: "Biotech, R&D, Science", name: "Food Science" },
			{ external_subcategory_id: 15447, category_name: "Biotech, R&D, Science", name: "Forensic Science" },
			{ external_subcategory_id: 11865, category_name: "Biotech, R&D, Science", name: "Materials & Physical Research" },
			{ external_subcategory_id: 11866, category_name: "Biotech, R&D, Science", name: "Mathematical & Statistical Research" },
			{ external_subcategory_id: 11921, category_name: "Biotech, R&D, Science", name: "Medical & Pharmaceutical Research" },
			{ external_subcategory_id: 11883, category_name: "Biotech, R&D, Science", name: "New Product R&D" },
			{ external_subcategory_id: 11912, category_name: "Biotech, R&D, Science", name: "General/Other - Science" },
			{ external_subcategory_id: 11835, category_name: "Construction, Architecture & Interior Design", name: "Air Conditioning, Heating & Refrigeration (HVAC)" },
			{ external_subcategory_id: 15448, category_name: "Construction, Architecture & Interior Design", name: "Architecture" },
			{ external_subcategory_id: 15449, category_name: "Construction, Architecture & Interior Design", name: "Building Contracts Administration" },
			{ external_subcategory_id: 11737, category_name: "Construction, Architecture & Interior Design", name: "CAD & Drafting" },
			{ external_subcategory_id: 11743, category_name: "Construction, Architecture & Interior Design", name: "Carpentry & Framing" },
			{ external_subcategory_id: 11755, category_name: "Construction, Architecture & Interior Design", name: "Concrete & Formworking" },
			{ external_subcategory_id: 15450, category_name: "Construction, Architecture & Interior Design", name: "Corporate & Management" },
			{ external_subcategory_id: 11829, category_name: "Construction, Architecture & Interior Design", name: "Demolition, Excavation & Heavy Equipment Operation" },
			{ external_subcategory_id: 11783, category_name: "Construction, Architecture & Interior Design", name: "Electrician" },
			{ external_subcategory_id: 11809, category_name: "Construction, Architecture & Interior Design", name: "Flooring, Tiling, Painting & Wallpapering" },
			{ external_subcategory_id: 11719, category_name: "Construction, Architecture & Interior Design", name: "Interior Design" },
			{ external_subcategory_id: 11845, category_name: "Construction, Architecture & Interior Design", name: "Ironwork & Metal Fabrication" },
			{ external_subcategory_id: 15451, category_name: "Construction, Architecture & Interior Design", name: "Landscape Architecture" },
			{ external_subcategory_id: 11896, category_name: "Construction, Architecture & Interior Design", name: "General/Other - Construction, Architecture & Interior Design" },
			{ external_subcategory_id: 11925, category_name: "Construction, Architecture & Interior Design", name: "Plumbing & Pipefitting" },
			{ external_subcategory_id: 11935, category_name: "Construction, Architecture & Interior Design", name: "Project Management" },
			{ external_subcategory_id: 11733, category_name: "Construction, Architecture & Interior Design", name: "Quantity Surveying, Estimating & Compliance" },
			{ external_subcategory_id: 11953, category_name: "Construction, Architecture & Interior Design", name: "Roofing" },
			{ external_subcategory_id: 11963, category_name: "Construction, Architecture & Interior Design", name: "Sheetrock & Plastering" },
			{ external_subcategory_id: 11965, category_name: "Construction, Architecture & Interior Design", name: "Site & Construction Management" },
			{ external_subcategory_id: 11978, category_name: "Construction, Architecture & Interior Design", name: "Surveying" },
			{ external_subcategory_id: 11726, category_name: "Customer Service & Call Centre", name: "Branch Staff" },
			{ external_subcategory_id: 11738, category_name: "Customer Service & Call Centre", name: "Contact & Call Centre" },
			{ external_subcategory_id: 11948, category_name: "Customer Service & Call Centre", name: "Customer Service" },
			{ external_subcategory_id: 11768, category_name: "Customer Service & Call Centre", name: "Customer Training" },
			{ external_subcategory_id: 11808, category_name: "Customer Service & Call Centre", name: "Flight Attendant" },
			{ external_subcategory_id: 11824, category_name: "Customer Service & Call Centre", name: "Hairdressing" },
			{ external_subcategory_id: 11985, category_name: "Customer Service & Call Centre", name: "IT Help Desk" },
			{ external_subcategory_id: 11898, category_name: "Customer Service & Call Centre", name: "General/Other - Customer Service & Call Centre" },
			{ external_subcategory_id: 11945, category_name: "Customer Service & Call Centre", name: "Reservations & Ticketing" },
			{ external_subcategory_id: 11710, category_name: "Customer Service & Call Centre", name: "Supervisors & Team Leaders" },
			{ external_subcategory_id: 11988, category_name: "Customer Service & Call Centre", name: "Telemarketing" },
			{ external_subcategory_id: 11775, category_name: "Editorial & Writing", name: "Digital Content Development" },
			{ external_subcategory_id: 11781, category_name: "Editorial & Writing", name: "Editing & Proofreading" },
			{ external_subcategory_id: 11850, category_name: "Editorial & Writing", name: "Journalist" },
			{ external_subcategory_id: 11899, category_name: "Editorial & Writing", name: "General/Other - Editorial & Writing" },
			{ external_subcategory_id: 11778, category_name: "Editorial & Writing", name: "Technical Writers" },
			{ external_subcategory_id: 11992, category_name: "Editorial & Writing", name: "Translation & Interpretation" },
			{ external_subcategory_id: 11708, category_name: "Education, Childcare & Training", name: "Academic Research" },
			{ external_subcategory_id: 11759, category_name: "Education, Childcare & Training", name: "Corporate Training & Development" },
			{ external_subcategory_id: 11768, category_name: "Education, Childcare & Training", name: "Customer Training" },
			{ external_subcategory_id: 11779, category_name: "Education, Childcare & Training", name: "Early Childhood" },
			{ external_subcategory_id: 11807, category_name: "Education, Childcare & Training", name: "Fitness & Sports Training" },
			{ external_subcategory_id: 11857, category_name: "Education, Childcare & Training", name: "Library & Archive" },
			{ external_subcategory_id: 15458, category_name: "Education, Childcare & Training", name: "Nanny & Babysitting" },
			{ external_subcategory_id: 11915, category_name: "Education, Childcare & Training", name: "General/Other - Education, Childcare & Training" },
			{ external_subcategory_id: 11748, category_name: "Education, Childcare & Training", name: "Primary Education" },
			{ external_subcategory_id: 11955, category_name: "Education, Childcare & Training", name: "School & University Administration" },
			{ external_subcategory_id: 11851, category_name: "Education, Childcare & Training", name: "Secondary Education" },
			{ external_subcategory_id: 11972, category_name: "Education, Childcare & Training", name: "Special Needs" },
			{ external_subcategory_id: 11995, category_name: "Education, Childcare & Training", name: "University" },
			{ external_subcategory_id: 11756, category_name: "Education, Childcare & Training", name: "Vocational Training & TAFE" },
			{ external_subcategory_id: 15459, category_name: "Engineering", name: "Administration & Technical Support" },
			{ external_subcategory_id: 11715, category_name: "Engineering", name: "Aeronautics & Aerospace" },
			{ external_subcategory_id: 15460, category_name: "Engineering", name: "Automotive Engineering" },
			{ external_subcategory_id: 11728, category_name: "Engineering", name: "Biomedical" },
			{ external_subcategory_id: 11737, category_name: "Engineering", name: "CAD & Drafting" },
			{ external_subcategory_id: 11746, category_name: "Engineering", name: "Chemical & Materials" },
			{ external_subcategory_id: 11747, category_name: "Engineering", name: "Civil/Structural" },
			{ external_subcategory_id: 11782, category_name: "Engineering", name: "Electrical & Electronics Engineering" },
			{ external_subcategory_id: 11786, category_name: "Engineering", name: "Energy & Nuclear Engineering" },
			{ external_subcategory_id: 11788, category_name: "Engineering", name: "Environmental Engineering" },
			{ external_subcategory_id: 15461, category_name: "Engineering", name: "Field Engineering" },
			{ external_subcategory_id: 11838, category_name: "Engineering", name: "Industrial & Manufacturing Engineering" },
			{ external_subcategory_id: 15462, category_name: "Engineering", name: "Management & Supervisory" },
			{ external_subcategory_id: 11881, category_name: "Engineering", name: "Marine" },
			{ external_subcategory_id: 11867, category_name: "Engineering", name: "Mechanical Engineering" },
			{ external_subcategory_id: 11900, category_name: "Engineering", name: "General/Other - Engineering" },
			{ external_subcategory_id: 15463, category_name: "Engineering", name: "Piping Engineering" },
			{ external_subcategory_id: 15464, category_name: "Engineering", name: "Product Development & Design" },
			{ external_subcategory_id: 15465, category_name: "Engineering", name: "Project Engineering" },
			{ external_subcategory_id: 11951, category_name: "Engineering", name: "RF & Wireless Engineering" },
			{ external_subcategory_id: 11980, category_name: "Engineering", name: "Systems & Process Engineering" },
			{ external_subcategory_id: 12003, category_name: "Engineering", name: "Water & Waste" },
			{ external_subcategory_id: 11734, category_name: "Executive & Strategic Management", name: "Analyst" },
			{ external_subcategory_id: 11929, category_name: "Executive & Strategic Management", name: "CEOs, Directors & Senior Managers" },
			{ external_subcategory_id: 11736, category_name: "Executive & Strategic Management", name: "Divisional Management" },
			{ external_subcategory_id: 11814, category_name: "Executive & Strategic Management", name: "Franchise & Business Ownership" },
			{ external_subcategory_id: 11830, category_name: "Executive & Strategic Management", name: "Hospital Administration & Patient Services" },
			{ external_subcategory_id: 11947, category_name: "Executive & Strategic Management", name: "Hospitality & Restaurant Management" },
			{ external_subcategory_id: 11860, category_name: "Executive & Strategic Management", name: "Management Consulting" },
			{ external_subcategory_id: 11875, category_name: "Executive & Strategic Management", name: "Mergers & Acquisitions" },
			{ external_subcategory_id: 11895, category_name: "Executive & Strategic Management", name: "General/Other - Business & Strategic Management" },
			{ external_subcategory_id: 11990, category_name: "Executive & Strategic Management", name: "Policy & Planning" },
			{ external_subcategory_id: 11955, category_name: "Executive & Strategic Management", name: "School & University Administration" },
			{ external_subcategory_id: 11975, category_name: "Executive & Strategic Management", name: "Store & Branch Management" },
			{ external_subcategory_id: 11976, category_name: "Executive & Strategic Management", name: "Strategy" },
			{ external_subcategory_id: 11785, category_name: "Government, Defence & Emergency", name: "Ambulance & Paramedic" },
			{ external_subcategory_id: 11762, category_name: "Government, Defence & Emergency", name: "Correctional Services" },
			{ external_subcategory_id: 11879, category_name: "Government, Defence & Emergency", name: "Defence Forces" },
			{ external_subcategory_id: 15468, category_name: "Government, Defence & Emergency", name: "Federal Government" },
			{ external_subcategory_id: 11805, category_name: "Government, Defence & Emergency", name: "Firefighting & Rescue" },
			{ external_subcategory_id: 15470, category_name: "Government, Defence & Emergency", name: "Local Government" },
			{ external_subcategory_id: 15469, category_name: "Government, Defence & Emergency", name: "General/Other - Government, Defence & Emergency" },
			{ external_subcategory_id: 11926, category_name: "Government, Defence & Emergency", name: "Police & Justice" },
			{ external_subcategory_id: 11990, category_name: "Government, Defence & Emergency", name: "Policy & Planning" },
			{ external_subcategory_id: 15472, category_name: "Government, Defence & Emergency", name: "State Government" },
			{ external_subcategory_id: 11820, category_name: "Health, Medical & Pharmaceutical", name: "Aged & Disability Care" },
			{ external_subcategory_id: 11785, category_name: "Health, Medical & Pharmaceutical", name: "Ambulance & Paramedic" },
			{ external_subcategory_id: 11749, category_name: "Health, Medical & Pharmaceutical", name: "Clinical Research" },
			{ external_subcategory_id: 11967, category_name: "Health, Medical & Pharmaceutical", name: "Community & Social Services" },
			{ external_subcategory_id: 11773, category_name: "Health, Medical & Pharmaceutical", name: "Dental" },
			{ external_subcategory_id: 11886, category_name: "Health, Medical & Pharmaceutical", name: "Dietary" },
			{ external_subcategory_id: 11830, category_name: "Health, Medical & Pharmaceutical", name: "Hospital Administration & Patient Services" },
			{ external_subcategory_id: 11878, category_name: "Health, Medical & Pharmaceutical", name: "Maternal, Midwifery & Obstetrics" },
			{ external_subcategory_id: 11872, category_name: "Health, Medical & Pharmaceutical", name: "Medical & Dental Assistants" },
			{ external_subcategory_id: 11921, category_name: "Health, Medical & Pharmaceutical", name: "Medical & Pharmaceutical Research" },
			{ external_subcategory_id: 15495, category_name: "Health, Medical & Pharmaceutical", name: "Medical & Pharmaceutical Sales" },
			{ external_subcategory_id: 11870, category_name: "Health, Medical & Pharmaceutical", name: "Medical Practitioners & Specialists" },
			{ external_subcategory_id: 11873, category_name: "Health, Medical & Pharmaceutical", name: "Mental Health" },
			{ external_subcategory_id: 15493, category_name: "Health, Medical & Pharmaceutical", name: "Natural & Massage Therapies" },
			{ external_subcategory_id: 11885, category_name: "Health, Medical & Pharmaceutical", name: "Nursing" },
			{ external_subcategory_id: 11891, category_name: "Health, Medical & Pharmaceutical", name: "Optical" },
			{ external_subcategory_id: 11908, category_name: "Health, Medical & Pharmaceutical", name: "General/Other - Health, Medical & Pharmaceutical" },
			{ external_subcategory_id: 11853, category_name: "Health, Medical & Pharmaceutical", name: "Pathology" },
			{ external_subcategory_id: 11922, category_name: "Health, Medical & Pharmaceutical", name: "Pharmacy" },
			{ external_subcategory_id: 11871, category_name: "Health, Medical & Pharmaceutical", name: "Physiotherapy, Occupational Therapy (OT) & Rehabilitation" },
			{ external_subcategory_id: 15494, category_name: "Health, Medical & Pharmaceutical", name: "Psychology & Counselling" },
			{ external_subcategory_id: 11936, category_name: "Health, Medical & Pharmaceutical", name: "Public Health Administration" },
			{ external_subcategory_id: 11938, category_name: "Health, Medical & Pharmaceutical", name: "Radiology & Sonography" },
			{ external_subcategory_id: 11973, category_name: "Health, Medical & Pharmaceutical", name: "Sports & Fitness Training" },
			{ external_subcategory_id: 12001, category_name: "Health, Medical & Pharmaceutical", name: "Veterinary & Zoology" },
			{ external_subcategory_id: 15467, category_name: "Hospitality, Travel & Tourism", name: "Casinos & Gaming" },
			{ external_subcategory_id: 11745, category_name: "Hospitality, Travel & Tourism", name: "Cooks & Chefs" },
			{ external_subcategory_id: 11794, category_name: "Hospitality, Travel & Tourism", name: "Event Planning & Coordination" },
			{ external_subcategory_id: 15466, category_name: "Hospitality, Travel & Tourism", name: "Flight Attendants & Other Airline Staff" },
			{ external_subcategory_id: 11811, category_name: "Hospitality, Travel & Tourism", name: "Food Preparation & Cooking" },
			{ external_subcategory_id: 11816, category_name: "Hospitality, Travel & Tourism", name: "Front Desk & Reception" },
			{ external_subcategory_id: 11822, category_name: "Hospitality, Travel & Tourism", name: "Guest Services & Concierge" },
			{ external_subcategory_id: 11947, category_name: "Hospitality, Travel & Tourism", name: "Hospitality & Restaurant Management" },
			{ external_subcategory_id: 11832, category_name: "Hospitality, Travel & Tourism", name: "Housekeeping" },
			{ external_subcategory_id: 11901, category_name: "Hospitality, Travel & Tourism", name: "General/Other - Hospitality, Travel & Tourism" },
			{ external_subcategory_id: 11831, category_name: "Hospitality, Travel & Tourism", name: "Restaurant Host & Hostess" },
			{ external_subcategory_id: 11823, category_name: "Hospitality, Travel & Tourism", name: "Tour Guides & Operators" },
			{ external_subcategory_id: 11993, category_name: "Hospitality, Travel & Tourism", name: "Travel & Ticketing Agents" },
			{ external_subcategory_id: 11810, category_name: "Hospitality, Travel & Tourism", name: "Wait Staff & Bartenders" },
			{ external_subcategory_id: 12007, category_name: "Hospitality, Travel & Tourism", name: "Wine Steward (Sommelier)" },
			{ external_subcategory_id: 11751, category_name: "HR & Recruitment", name: "Compensation & Benefits Policy" },
			{ external_subcategory_id: 11777, category_name: "HR & Recruitment", name: "Compliance, Employee & Industrial Relations" },
			{ external_subcategory_id: 11759, category_name: "HR & Recruitment", name: "Corporate Training & Development" },
			{ external_subcategory_id: 11796, category_name: "HR & Recruitment", name: "Executive Recruitment" },
			{ external_subcategory_id: 14870, category_name: "HR & Recruitment", name: "HR Consulting" },
			{ external_subcategory_id: 15473, category_name: "HR & Recruitment", name: "HR Managers & Directors" },
			{ external_subcategory_id: 11887, category_name: "HR & Recruitment", name: "Occupational Health & Safety (OH&S)" },
			{ external_subcategory_id: 11902, category_name: "HR & Recruitment", name: "General/Other - HR & Recruitment" },
			{ external_subcategory_id: 11918, category_name: "HR & Recruitment", name: "Payroll & Benefits Administration" },
			{ external_subcategory_id: 11943, category_name: "HR & Recruitment", name: "Recruitment Consulting" },
			{ external_subcategory_id: 11712, category_name: "Insurance & Superannuation", name: "Actuarial & Analysis" },
			{ external_subcategory_id: 14866, category_name: "Insurance & Superannuation", name: "Assessors & Claims" },
			{ external_subcategory_id: 15481, category_name: "Insurance & Superannuation", name: "Health Insurance" },
			{ external_subcategory_id: 15482, category_name: "Insurance & Superannuation", name: "Insurance Compliance & Risk" },
			{ external_subcategory_id: 11839, category_name: "Insurance & Superannuation", name: "Insurance Sales & Broking" },
			{ external_subcategory_id: 15480, category_name: "Insurance & Superannuation", name: "General/Other - Insurance & Superannuation" },
			{ external_subcategory_id: 15483, category_name: "Insurance & Superannuation", name: "Superannuation & Life Insurance" },
			{ external_subcategory_id: 11927, category_name: "Insurance & Superannuation", name: "Underwriting" },
			{ external_subcategory_id: 15484, category_name: "Insurance & Superannuation", name: "Workers' Compensation" },
			{ external_subcategory_id: 11979, category_name: "IT", name: "Business & Systems Analysis" },
			{ external_subcategory_id: 11771, category_name: "IT", name: "Data Warehousing" },
			{ external_subcategory_id: 11772, category_name: "IT", name: "Database Development & Admin" },
			{ external_subcategory_id: 11787, category_name: "IT", name: "Enterprise Software Implementation & Consulting" },
			{ external_subcategory_id: 11825, category_name: "IT", name: "Hardware Engineering" },
			{ external_subcategory_id: 11774, category_name: "IT", name: "Helpdesk & Support" },
			{ external_subcategory_id: 11996, category_name: "IT", name: "Information Architecture (IA) & Usability" },
			{ external_subcategory_id: 11847, category_name: "IT", name: "IT Consulting" },
			{ external_subcategory_id: 11985, category_name: "IT", name: "IT Help Desk" },
			{ external_subcategory_id: 15485, category_name: "IT", name: "IT Managers & Directors" },
			{ external_subcategory_id: 11986, category_name: "IT", name: "IT Pre & Post Sales" },
			{ external_subcategory_id: 11848, category_name: "IT", name: "IT Project Management" },
			{ external_subcategory_id: 11971, category_name: "IT", name: "IT Training" },
			{ external_subcategory_id: 15486, category_name: "IT", name: "Mobile" },
			{ external_subcategory_id: 11882, category_name: "IT", name: "Networks & Systems Administration" },
			{ external_subcategory_id: 11883, category_name: "IT", name: "New Product R&D" },
			{ external_subcategory_id: 11904, category_name: "IT", name: "General/Other - IT" },
			{ external_subcategory_id: 11754, category_name: "IT", name: "Security" },
			{ external_subcategory_id: 11970, category_name: "IT", name: "Software Engineering" },
			{ external_subcategory_id: 11968, category_name: "IT", name: "Software Quality Assurance" },
			{ external_subcategory_id: 11969, category_name: "IT", name: "Software & System Architecture" },
			{ external_subcategory_id: 11778, category_name: "IT", name: "Technical Writers" },
			{ external_subcategory_id: 11987, category_name: "IT", name: "Telecommunications" },
			{ external_subcategory_id: 12005, category_name: "IT", name: "User Interface (UI), User Experience (UX) & Web Design" },
			{ external_subcategory_id: 12004, category_name: "IT", name: "Web Producers & Web Masters" },
			{ external_subcategory_id: 11727, category_name: "Legal", name: "Barrister" },
			{ external_subcategory_id: 15487, category_name: "Legal", name: "Commercial & Corporate Law" },
			{ external_subcategory_id: 11944, category_name: "Legal", name: "Compliance & Trade Practices Law" },
			{ external_subcategory_id: 11757, category_name: "Legal", name: "Contracts Administration" },
			{ external_subcategory_id: 11767, category_name: "Legal", name: "Criminal Law" },
			{ external_subcategory_id: 11852, category_name: "Legal", name: "Employment Law" },
			{ external_subcategory_id: 15488, category_name: "Legal", name: "Environmental Law" },
			{ external_subcategory_id: 11799, category_name: "Legal", name: "Family Law" },
			{ external_subcategory_id: 11917, category_name: "Legal", name: "Intellectual Property Law" },
			{ external_subcategory_id: 11916, category_name: "Legal", name: "Legal Secretaries, Paralegals & Clerical" },
			{ external_subcategory_id: 11905, category_name: "Legal", name: "General/Other - Legal" },
			{ external_subcategory_id: 11941, category_name: "Legal", name: "Property Law" },
			{ external_subcategory_id: 11722, category_name: "Legal", name: "Solicitor" },
			{ external_subcategory_id: 11983, category_name: "Legal", name: "Tax Law" },
			{ external_subcategory_id: 11717, category_name: "Logistics, Supply & Transport", name: "Aircraft Maintenance" },
			{ external_subcategory_id: 11742, category_name: "Logistics, Supply & Transport", name: "Baggage Handler" },
			{ external_subcategory_id: 11739, category_name: "Logistics, Supply & Transport", name: "Car, Van & Bus Drivers" },
			{ external_subcategory_id: 11763, category_name: "Logistics, Supply & Transport", name: "Cost Estimating" },
			{ external_subcategory_id: 11876, category_name: "Logistics, Supply & Transport", name: "Courier" },
			{ external_subcategory_id: 11793, category_name: "Logistics, Supply & Transport", name: "Equipment, Forklift & Crane Operation" },
			{ external_subcategory_id: 11827, category_name: "Logistics, Supply & Transport", name: "Hazardous Materials Handling" },
			{ external_subcategory_id: 11836, category_name: "Logistics, Supply & Transport", name: "Importer & Exporter" },
			{ external_subcategory_id: 11842, category_name: "Logistics, Supply & Transport", name: "Inventory Control & Production" },
			{ external_subcategory_id: 11874, category_name: "Logistics, Supply & Transport", name: "Merchandising, Product Planning & Buying" },
			{ external_subcategory_id: 11906, category_name: "Logistics, Supply & Transport", name: "General/Other - Logistics, Supply & Transport" },
			{ external_subcategory_id: 11924, category_name: "Logistics, Supply & Transport", name: "Pilot" },
			{ external_subcategory_id: 11937, category_name: "Logistics, Supply & Transport", name: "Purchasing & Procurement" },
			{ external_subcategory_id: 11964, category_name: "Logistics, Supply & Transport", name: "Shipping, Receiving, Warehousing & Customs" },
			{ external_subcategory_id: 11977, category_name: "Logistics, Supply & Transport", name: "Supply Chain Management" },
			{ external_subcategory_id: 11991, category_name: "Logistics, Supply & Transport", name: "Transport" },
			{ external_subcategory_id: 11994, category_name: "Logistics, Supply & Transport", name: "Truck Drivers" },
			{ external_subcategory_id: 11998, category_name: "Logistics, Supply & Transport", name: "Vehicle Dispatch, Routing & Scheduling" },
			{ external_subcategory_id: 15489, category_name: "Logistics, Supply & Transport", name: "Vehicle Hire, Leasing & Fleet" },
			{ external_subcategory_id: 11999, category_name: "Logistics, Supply & Transport", name: "Vehicle Inspection" },
			{ external_subcategory_id: 11877, category_name: "Manufacturing & Industrial", name: "Boiler Making, Fitting, Welding & Metalworking" },
			{ external_subcategory_id: 11792, category_name: "Manufacturing & Industrial", name: "Equipment Operations" },
			{ external_subcategory_id: 11859, category_name: "Manufacturing & Industrial", name: "Fitting, Machining & Computer Numerical Control (CNC)" },
			{ external_subcategory_id: 11827, category_name: "Manufacturing & Industrial", name: "Hazardous Materials Handling" },
			{ external_subcategory_id: 11837, category_name: "Manufacturing & Industrial", name: "Industrial Design" },
			{ external_subcategory_id: 11855, category_name: "Manufacturing & Industrial", name: "Layout, Prepress, Printing, & Binding Operations" },
			{ external_subcategory_id: 11909, category_name: "Manufacturing & Industrial", name: "General/Other - Manufacturing & Industrial" },
			{ external_subcategory_id: 11933, category_name: "Manufacturing & Industrial", name: "Planning & Scheduling" },
			{ external_subcategory_id: 11721, category_name: "Manufacturing & Industrial", name: "Process & Assembly Line Work" },
			{ external_subcategory_id: 11932, category_name: "Manufacturing & Industrial", name: "Production Quality Assurance" },
			{ external_subcategory_id: 11937, category_name: "Manufacturing & Industrial", name: "Purchasing & Procurement" },
			{ external_subcategory_id: 11964, category_name: "Manufacturing & Industrial", name: "Shipping, Receiving, Warehousing & Customs" },
			{ external_subcategory_id: 11966, category_name: "Manufacturing & Industrial", name: "Six Sigma, Black Belt & Total Quality Management (TQM)" },
			{ external_subcategory_id: 11890, category_name: "Manufacturing & Industrial", name: "Supervisors & Plant Management" },
			{ external_subcategory_id: 11987, category_name: "Manufacturing & Industrial", name: "Telecommunications" },
			{ external_subcategory_id: 11962, category_name: "Manufacturing & Industrial", name: "Textiles & Footwear" },
			{ external_subcategory_id: 11880, category_name: "Manufacturing & Industrial", name: "Toolmaking" },
			{ external_subcategory_id: 12003, category_name: "Manufacturing & Industrial", name: "Water & Waste" },
			{ external_subcategory_id: 11732, category_name: "Marketing", name: "Brand Marketing" },
			{ external_subcategory_id: 11758, category_name: "Marketing", name: "Copywriter" },
			{ external_subcategory_id: 11776, category_name: "Marketing", name: "Direct Marketing & Customer Relationship Management (CRM)" },
			{ external_subcategory_id: 11862, category_name: "Marketing", name: "Market Research & Analysis" },
			{ external_subcategory_id: 11863, category_name: "Marketing", name: "Marketing Communications" },
			{ external_subcategory_id: 15490, category_name: "Marketing", name: "Marketing Managers, Directors & Consultants" },
			{ external_subcategory_id: 11869, category_name: "Marketing", name: "Media Planning & Buying" },
			{ external_subcategory_id: 15491, category_name: "Marketing", name: "Online & Search Engine Marketing" },
			{ external_subcategory_id: 11907, category_name: "Marketing", name: "General/Other - Marketing" },
			{ external_subcategory_id: 11931, category_name: "Marketing", name: "Product Management" },
			{ external_subcategory_id: 11864, category_name: "Marketing", name: "Production & Traffic" },
			{ external_subcategory_id: 11844, category_name: "Marketing", name: "Public, Media & Investor Relations" },
			{ external_subcategory_id: 11795, category_name: "Marketing", name: "Sponsorship, Promotions & Event Management" },
			{ external_subcategory_id: 11988, category_name: "Marketing", name: "Telemarketing" },
			{ external_subcategory_id: 15492, category_name: "Marketing", name: "Trade Marketing" },
			{ external_subcategory_id: 12002, category_name: "Marketing", name: "Visual & Display Merchandising" },
			{ external_subcategory_id: 15496, category_name: "Mining, Oil & Gas", name: "Corporate & Administrative" },
			{ external_subcategory_id: 15497, category_name: "Mining, Oil & Gas", name: "Drilling" },
			{ external_subcategory_id: 15498, category_name: "Mining, Oil & Gas", name: "Engineering" },
			{ external_subcategory_id: 11789, category_name: "Mining, Oil & Gas", name: "Environment & Safety" },
			{ external_subcategory_id: 11790, category_name: "Mining, Oil & Gas", name: "Environmental/Geological Testing & Analysis" },
			{ external_subcategory_id: 15499, category_name: "Mining, Oil & Gas", name: "Exploration" },
			{ external_subcategory_id: 15500, category_name: "Mining, Oil & Gas", name: "Field Management & Supervisory" },
			{ external_subcategory_id: 15502, category_name: "Mining, Oil & Gas", name: "Maintenance" },
			{ external_subcategory_id: 15503, category_name: "Mining, Oil & Gas", name: "Metallurgy" },
			{ external_subcategory_id: 15504, category_name: "Mining, Oil & Gas", name: "Mineral Processing" },
			{ external_subcategory_id: 11889, category_name: "Mining, Oil & Gas", name: "Oil & Gas" },
			{ external_subcategory_id: 15501, category_name: "Mining, Oil & Gas", name: "General/Other - Mining, Oil & Gas" },
			{ external_subcategory_id: 15505, category_name: "Mining, Oil & Gas", name: "Production" },
			{ external_subcategory_id: 11741, category_name: "Other", name: "Career Expos" },
			{ external_subcategory_id: 11814, category_name: "Other", name: "Franchise & Business Ownership" },
			{ external_subcategory_id: 11892, category_name: "Other", name: "Other" },
			{ external_subcategory_id: 12008, category_name: "Other", name: "Work from Home" },
			{ external_subcategory_id: 11794, category_name: "Program & Project Management", name: "Event Planning & Coordination" },
			{ external_subcategory_id: 11848, category_name: "Program & Project Management", name: "IT Project Management" },
			{ external_subcategory_id: 11910, category_name: "Program & Project Management", name: "General/Other - Project & Program Management" },
			{ external_subcategory_id: 11934, category_name: "Program & Project Management", name: "Program Management" },
			{ external_subcategory_id: 11935, category_name: "Program & Project Management", name: "Project Management" },
			{ external_subcategory_id: 11713, category_name: "Property & Real Estate", name: "Administration" },
			{ external_subcategory_id: 11939, category_name: "Property & Real Estate", name: "Commercial & Residential Sales" },
			{ external_subcategory_id: 15507, category_name: "Property & Real Estate", name: "General/Other - Property & Real Estate" },
			{ external_subcategory_id: 14874, category_name: "Property & Real Estate", name: "Property & Asset Management" },
			{ external_subcategory_id: 11833, category_name: "Property & Real Estate", name: "Property Development" },
			{ external_subcategory_id: 11941, category_name: "Property & Real Estate", name: "Property Law" },
			{ external_subcategory_id: 14875, category_name: "Property & Real Estate", name: "Real Estate Leasing & Acquisition" },
			{ external_subcategory_id: 11940, category_name: "Property & Real Estate", name: "Valuation" },
			{ external_subcategory_id: 11789, category_name: "Quality Assurance & Safety", name: "Environment & Safety" },
			{ external_subcategory_id: 11813, category_name: "Quality Assurance & Safety", name: "Food Safety & Inspection" },
			{ external_subcategory_id: 11815, category_name: "Quality Assurance & Safety", name: "Fraud Investigation" },
			{ external_subcategory_id: 11846, category_name: "Quality Assurance & Safety", name: "ISO Certification" },
			{ external_subcategory_id: 11887, category_name: "Quality Assurance & Safety", name: "Occupational Health & Safety (OH&S)" },
			{ external_subcategory_id: 11911, category_name: "Quality Assurance & Safety", name: "General/Other - Quality Assurance & Safety" },
			{ external_subcategory_id: 11932, category_name: "Quality Assurance & Safety", name: "Production Quality Assurance" },
			{ external_subcategory_id: 11733, category_name: "Quality Assurance & Safety", name: "Quantity Surveying, Estimating & Compliance" },
			{ external_subcategory_id: 11966, category_name: "Quality Assurance & Safety", name: "Six Sigma, Black Belt & Total Quality Management (TQM)" },
			{ external_subcategory_id: 11968, category_name: "Quality Assurance & Safety", name: "Software Quality Assurance" },
			{ external_subcategory_id: 11999, category_name: "Quality Assurance & Safety", name: "Vehicle Inspection" },
			{ external_subcategory_id: 11950, category_name: "Retail", name: "Counter Sales & Cashier" },
			{ external_subcategory_id: 11800, category_name: "Retail", name: "Fashion & Accessories" },
			{ external_subcategory_id: 11874, category_name: "Retail", name: "Merchandising, Product Planning & Buying" },
			{ external_subcategory_id: 15508, category_name: "Retail", name: "General/Other - Retail" },
			{ external_subcategory_id: 14877, category_name: "Retail", name: "Retail Management" },
			{ external_subcategory_id: 11975, category_name: "Retail", name: "Store & Branch Management" },
			{ external_subcategory_id: 11974, category_name: "Retail", name: "Store Security & Loss Prevention" },
			{ external_subcategory_id: 12002, category_name: "Retail", name: "Visual & Display Merchandising" },
			{ external_subcategory_id: 11709, category_name: "Sales", name: "Account & Relationship Management" },
			{ external_subcategory_id: 11735, category_name: "Sales", name: "Business Development" },
			{ external_subcategory_id: 11939, category_name: "Sales", name: "Commercial & Residential Sales" },
			{ external_subcategory_id: 11950, category_name: "Sales", name: "Counter Sales & Cashier" },
			{ external_subcategory_id: 11801, category_name: "Sales", name: "Field Sales" },
			{ external_subcategory_id: 11839, category_name: "Sales", name: "Insurance Sales & Broking" },
			{ external_subcategory_id: 11840, category_name: "Sales", name: "International Sales" },
			{ external_subcategory_id: 11986, category_name: "Sales", name: "IT Pre & Post Sales" },
			{ external_subcategory_id: 11868, category_name: "Sales", name: "Media & Advertising Sales" },
			{ external_subcategory_id: 15495, category_name: "Sales", name: "Medical & Pharmaceutical Sales" },
			{ external_subcategory_id: 11913, category_name: "Sales", name: "General/Other - Sales" },
			{ external_subcategory_id: 11943, category_name: "Sales", name: "Recruitment Consulting" },
			{ external_subcategory_id: 15509, category_name: "Sales", name: "Sales Management" },
			{ external_subcategory_id: 11954, category_name: "Sales", name: "Sales Support & Operations" },
			{ external_subcategory_id: 11989, category_name: "Sales", name: "Telesales" },
			{ external_subcategory_id: 11993, category_name: "Sales", name: "Travel & Ticketing Agents" },
			{ external_subcategory_id: 12006, category_name: "Sales", name: "Wholesale & Reselling Sales" },
			{ external_subcategory_id: 11718, category_name: "Security & Protective Services", name: "Airport Security & Screening" },
			{ external_subcategory_id: 11762, category_name: "Security & Protective Services", name: "Correctional Services" },
			{ external_subcategory_id: 11879, category_name: "Security & Protective Services", name: "Defence Forces" },
			{ external_subcategory_id: 11805, category_name: "Security & Protective Services", name: "Firefighting & Rescue" },
			{ external_subcategory_id: 11815, category_name: "Security & Protective Services", name: "Fraud Investigation" },
			{ external_subcategory_id: 11858, category_name: "Security & Protective Services", name: "Locksmith" },
			{ external_subcategory_id: 11914, category_name: "Security & Protective Services", name: "General/Other - Security & Protective Services" },
			{ external_subcategory_id: 11926, category_name: "Security & Protective Services", name: "Police & Justice" },
			{ external_subcategory_id: 11961, category_name: "Security & Protective Services", name: "Security & Protection Service" },
			{ external_subcategory_id: 11974, category_name: "Security & Protective Services", name: "Store Security & Loss Prevention" },
			{ external_subcategory_id: 11835, category_name: "Trades & Services", name: "Air Conditioning, Heating & Refrigeration (HVAC)" },
			{ external_subcategory_id: 15506, category_name: "Trades & Services", name: "Apprenticeships" },
			{ external_subcategory_id: 15474, category_name: "Trades & Services", name: "Bakers, Butchers & Grocers" },
			{ external_subcategory_id: 15457, category_name: "Trades & Services", name: "Beauty Therapy & Make-Up" },
			{ external_subcategory_id: 11877, category_name: "Trades & Services", name: "Boiler Making, Fitting, Welding & Metalworking" },
			{ external_subcategory_id: 15476, category_name: "Trades & Services", name: "Bricklaying" },
			{ external_subcategory_id: 11743, category_name: "Trades & Services", name: "Carpentry & Framing" },
			{ external_subcategory_id: 11753, category_name: "Trades & Services", name: "Computer, Electronics & Telecomm Servicing" },
			{ external_subcategory_id: 11755, category_name: "Trades & Services", name: "Concrete & Formworking" },
			{ external_subcategory_id: 15477, category_name: "Trades & Services", name: "Dressmaker" },
			{ external_subcategory_id: 11783, category_name: "Trades & Services", name: "Electrician" },
			{ external_subcategory_id: 11791, category_name: "Trades & Services", name: "Equipment Install, Maintain & Repair" },
			{ external_subcategory_id: 11859, category_name: "Trades & Services", name: "Fitting, Machining & Computer Numerical Control (CNC)" },
			{ external_subcategory_id: 11809, category_name: "Trades & Services", name: "Flooring, Tiling, Painting & Wallpapering" },
			{ external_subcategory_id: 15478, category_name: "Trades & Services", name: "Florist" },
			{ external_subcategory_id: 11854, category_name: "Trades & Services", name: "Gardens, Trees & Landscapes" },
			{ external_subcategory_id: 11824, category_name: "Trades & Services", name: "Hairdressing" },
			{ external_subcategory_id: 15479, category_name: "Trades & Services", name: "Labourer" },
			{ external_subcategory_id: 11858, category_name: "Trades & Services", name: "Locksmith" },
			{ external_subcategory_id: 11798, category_name: "Trades & Services", name: "Maintenance & Handypersons" },
			{ external_subcategory_id: 11903, category_name: "Trades & Services", name: "General/Other - Trades & Services" },
			{ external_subcategory_id: 11925, category_name: "Trades & Services", name: "Plumbing & Pipefitting" },
			{ external_subcategory_id: 11849, category_name: "Trades & Services", name: "Residential & Business Cleaning" },
			{ external_subcategory_id: 11953, category_name: "Trades & Services", name: "Roofing" },
			{ external_subcategory_id: 11963, category_name: "Trades & Services", name: "Sheetrock & Plastering" },
			{ external_subcategory_id: 12000, category_name: "Trades & Services", name: "Vehicle Parts, Maintenance & Repair" },
			{ external_subcategory_id: 15511, category_name: "Voluntary, Charity & Social Work", name: "Associations, Not For Profit & Charities" },
			{ external_subcategory_id: 11967, category_name: "Voluntary, Charity & Social Work", name: "Community & Social Services" },
			{ external_subcategory_id: 11818, category_name: "Voluntary, Charity & Social Work", name: "Fundraising" },
			{ external_subcategory_id: 15512, category_name: "Voluntary, Charity & Social Work", name: "General/Other - Voluntary, Charity & Social Work" },
			{ external_subcategory_id: 15513, category_name: "Voluntary, Charity & Social Work", name: "Religion & Church" }
		]
		JobSubcategory.delete_all
		subcategories.each do |s|
			subcategory_obj = OpenStruct.new(s)
			job_category = JobCategory.where(name: subcategory_obj.category_name).first
			subcategory = JobSubcategory.find_or_initialize_by_external_subcategory_id(subcategory_obj.external_subcategory_id)
			subcategory.name = subcategory_obj.name
			subcategory.external_subcategory_id = subcategory_obj.external_subcategory_id
			subcategory.job_category_id = job_category.id
			subcategory.save
		end
	end
end