require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::BountiesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Bounty. As you add validations to Admin::Bounty, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::BountiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_bounties as @admin_bounties" do
      bounty = Admin::Bounty.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_bounties).should eq([bounty])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_bounty as @admin_bounty" do
      bounty = Admin::Bounty.create! valid_attributes
      get :show, {:id => bounty.to_param}, valid_session
      assigns(:admin_bounty).should eq(bounty)
    end
  end

  describe "GET new" do
    it "assigns a new admin_bounty as @admin_bounty" do
      get :new, {}, valid_session
      assigns(:admin_bounty).should be_a_new(Admin::Bounty)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_bounty as @admin_bounty" do
      bounty = Admin::Bounty.create! valid_attributes
      get :edit, {:id => bounty.to_param}, valid_session
      assigns(:admin_bounty).should eq(bounty)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Bounty" do
        expect {
          post :create, {:admin_bounty => valid_attributes}, valid_session
        }.to change(Admin::Bounty, :count).by(1)
      end

      it "assigns a newly created admin_bounty as @admin_bounty" do
        post :create, {:admin_bounty => valid_attributes}, valid_session
        assigns(:admin_bounty).should be_a(Admin::Bounty)
        assigns(:admin_bounty).should be_persisted
      end

      it "redirects to the created admin_bounty" do
        post :create, {:admin_bounty => valid_attributes}, valid_session
        response.should redirect_to(Admin::Bounty.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_bounty as @admin_bounty" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Bounty.any_instance.stub(:save).and_return(false)
        post :create, {:admin_bounty => {  }}, valid_session
        assigns(:admin_bounty).should be_a_new(Admin::Bounty)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Bounty.any_instance.stub(:save).and_return(false)
        post :create, {:admin_bounty => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_bounty" do
        bounty = Admin::Bounty.create! valid_attributes
        # Assuming there are no other admin_bounties in the database, this
        # specifies that the Admin::Bounty created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Bounty.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => bounty.to_param, :admin_bounty => { "these" => "params" }}, valid_session
      end

      it "assigns the requested admin_bounty as @admin_bounty" do
        bounty = Admin::Bounty.create! valid_attributes
        put :update, {:id => bounty.to_param, :admin_bounty => valid_attributes}, valid_session
        assigns(:admin_bounty).should eq(bounty)
      end

      it "redirects to the admin_bounty" do
        bounty = Admin::Bounty.create! valid_attributes
        put :update, {:id => bounty.to_param, :admin_bounty => valid_attributes}, valid_session
        response.should redirect_to(bounty)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_bounty as @admin_bounty" do
        bounty = Admin::Bounty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Bounty.any_instance.stub(:save).and_return(false)
        put :update, {:id => bounty.to_param, :admin_bounty => {  }}, valid_session
        assigns(:admin_bounty).should eq(bounty)
      end

      it "re-renders the 'edit' template" do
        bounty = Admin::Bounty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Bounty.any_instance.stub(:save).and_return(false)
        put :update, {:id => bounty.to_param, :admin_bounty => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_bounty" do
      bounty = Admin::Bounty.create! valid_attributes
      expect {
        delete :destroy, {:id => bounty.to_param}, valid_session
      }.to change(Admin::Bounty, :count).by(-1)
    end

    it "redirects to the admin_bounties list" do
      bounty = Admin::Bounty.create! valid_attributes
      delete :destroy, {:id => bounty.to_param}, valid_session
      response.should redirect_to(admin_bounties_url)
    end
  end

end
