# Mandrill
SMTP_ADDRESS: smtp.mandrillapp.com
SMTP_USERNAME: dev@accruto.com
SMTP_PASSWORD: dzBUUTqDJEYqc3D_TRERMQ
CAREERONE_CAT_CODE: 1:EAAQZyQFf8jEXJ9WtzRkrCcuPhqurTr_Tc587b4Z66UWXcpVIXlbov2N9nVvWjN4xxyljwGigzAhsl2tPDBrf8e7jn99.0iIkRUmRFQ7Un4Gl_6dtdAqUfXiHUm0g4PDBvuM2_ysBk8eTlJ4vctXI_UtVw--

development:
 SMTP_DOMAIN: http://localhost:3000

staging:
 SMTP_DOMAIN: http://staging.accruto.com

production:
 SMTP_DOMAIN: http://accruto.com
