development:
  adapter: postgresql
  encoding: utf8
  database: accruto
  username: johnkuehyoongfook
  password:
  host: localhost

staging:
  adapter: postgresql
  encoding: utf8
  database: accruto-staging
  username: johnkuehyoongfook
  password:
  host: localhost